services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: fashionstore-backend-container

    ports:
      - "3000:3000"

    env_file:
      - ./backend/.env

    restart: unless-stopped